<?php

/**
 * @file
 * Hook implementations for htmx_plus module.
 */

/**
 * Implements hook_theme().
 *
 * @return array<string, array<string, array<string, null>|string>>.
 *   An associative array of theme hooks and their definitions.
 */
function htmx_plus_theme(): array {
  return [
    'htmx_plus_build_random_number' => [
      'variables' => [
        'button_text' => NULL,
      ],
      'template' => 'htmx-plus-build-random-number',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 *
 * @param array<string,array<string,array<int,string>>> &$attachments
 *   The attachments array.
 */
function htmx_plus_page_attachments(array &$attachments): void {

  /** @var \Drupal\htmx_plus\HtmxLibraryAttacher $htmxLibraryAttacher **/
  $htmxLibraryAttacher = \Drupal::service('htmx_plus.htmx_library_attacher');
  $htmxLibraryAttacher->attachLibraryIfAvailable($attachments);
}
