<?php

/**
 * @file
 * Hook implementations for htmx_plus_web_1_0_app module.
 */

/**
 * Implements hook_theme().
 *
 * @phpstan-return array<string, array<string, mixed>>
 *   An array of theme hook definitions.
 */
function htmx_plus_web_1_0_app_theme(): array {
  return [
    'contacts_page' => [
      'variables' => [
        'contacts' => [],
        'search_query' => [],
      ],
    ],
    'contacts_new' => [
      'variables' => [
        'contact' => [],
        'validationResult' => [],
      ],
    ],
    'contact_show' => [
      'variables' => [
        'contact' => [],
      ],
    ],
    'contact_edit' => [
      'variables' => [
        'contact' => [],
        'validationResult' => [],
      ],
    ],
    'get_the_contacts_button_block' => [
      'variables' => [
        'button_text' => '',
      ],
    ],
    'contacts_list' => [
      'variables' => [
        'contacts' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 *
 * @phpstan-param array<string, mixed> $variables
 *   An associative array.
 *
 * @phpstan-return void
 */
function htmx_plus_web_1_0_app_preprocess_page(array &$variables): void {
  $search_query = \Drupal::request()->query->get('q', '');
  $variables['search_query'] = $search_query;
}
